beardgame/graphics

- src/amulware.Graphics/amulware.Graphics.csproj
I have changed the target .NET framework from Core 4.0 to 4.5, since I have some issues compiling as is: the Core 4.0 is not supported by Mono on non-Windows machines (so you need to change it to a normal 4.0). Also, since the referenced beardgame/utilities has .NET 4.5 as target, I got into some troubles compiling this against 4.0 (or it may be that my own projects targeting .NET 4.5 are causing the problems) as well.
> Changed target network to 4.5.

- src/amulware.Graphics/Core/vertexdata/VertexData.cs
- src/amulware.Graphics/amulware.Graphics.csproj
In particular:
* Use newer language features where relevant
* Use immutable dictionaries to reveal that they are constant
* Document ambiguous `defaultNormalize` parameter
> 💄 Clean up vertexdata class

- src/amulware.Graphics/Charts/FastChart2DBarVertex.cs
- src/amulware.Graphics/Core/vertexdata/IVertexData.cs
- src/amulware.Graphics/Core/vertexdata/VertexAttributeTemplate.cs
- src/amulware.Graphics/Core/vertexdata/VertexData.cs
- src/amulware.Graphics/Meshes/MeshVertex.cs
The class was a bit of a mess, so I did the following:
- remove #region because I really don't like how they clutter things anymore
- remove the internal AttributeTypeInfo in favour of simpler tuples
- remove the IAttributeTemplate interface and just expose the only implementation of it directly
- move that implementation to its own file
This is a breaking change, but source compatibility is maintained, so it's not a big deal.
I also removed IVertexData.Size which was never used.
> 🧹 Clean up VertexData helper class

- src/amulware.Graphics/Text/Font.cs
- src/amulware.Graphics/Text/FontFactory.cs
* `TryGetCharacterInfoFor` was added. It will return false if it can't find the character.
* `GetCharacterInfoFor` will no longer throw, and return a fallback glyph.
* The fallback glyph is automatically used for string measuring.
> 🔡 Use a fallback glyph for fonts

- examples/01.Basics/GameWindow.cs
- examples/01.Basics/amulware.Graphics.Examples.01.Basics.csproj
- examples/02.IndexBuffer/GameWindow.cs
- examples/02.IndexBuffer/amulware.Graphics.Examples.02.IndexBuffer.csproj
- examples/08.PostProcessing/GameWindow.cs
- examples/08.PostProcessing/amulware.Graphics.Examples.08.PostProcessing.csproj
- examples/12.Text/GameWindow.cs
- examples/12.Text/UVVertexData.cs
- examples/12.Text/amulware.Graphics.Examples.12.Text.csproj
- examples/20.Mandelbrot/amulware.Graphics.Examples.20.Mandelbrot.csproj
The examples were broken for a variety of reasons:
1. OpenTK was updated, but the examples were still built on the old OpenTK references.
2. Breaking changes were made to the shape and text drawers. The examples weren't updated.
This PR addresses both. I ran all the examples locally and the ran successfully.
> 🧯 Fix the examples

- Bearded.Graphics/Windowing/Window.cs
Right now, the window class draws 100% CPU by fetching UI events as fast as possible.
Instead, ~1000 times a second is plenty and reduces CPU time to almost nothing.
Down the line, we should refactor this to wait until there are new events to handle.
🧵.💤
It's simple and the class isn't great anyway. It'll do for now.
> 🐢 Reduce CPU usage of window UI thread

- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-publish.yml
- Bearded.Graphics.Examples/01.Basics/GameWindow.cs
- Bearded.Graphics.Examples/02.IndexBuffer/GameWindow.cs
- Bearded.Graphics.Examples/08.PostProcessing/GameWindow.cs
- Bearded.Graphics.Examples/12.Text/GameWindow.cs
- Bearded.Graphics.Examples/20.Mandelbrot/GameWindow.cs
- Bearded.Graphics/Bearded.Graphics.csproj
- Bearded.Graphics/Bearded.Graphics.nuspec
Adds support for GitHub actions for this repository.
Closes #39 and #40
I want to be able to rely on Graphics to implement other projects without having to submodule the library.
Copies the templates from beardgame/.github
Then:
* Fixes the examples so they build again
* Removes some superfluous build flags from `Bearded.Graphics.csproj` which were leading to race conditions
* Adds a nuspec file so we can upload the library to nuspec.
N/A
Should be straightforward. Review the nuspec file as needed.
> 👷‍♂️ Add GitHub actions support

- Bearded.Graphics/Shapes/ShapeDrawer2.cs
This PR fixes a bug that causes lines to be drawn at twice the width that is specified in `lineWidth`
It's a bug. Specifically, this creates an inconsistent API with the other draw methods, that do consider `lineWidth` as their actual line width:
(Note: this image uses a new arc drawing function, but this is directly copied from the circle drawing function in this library).
The line drawing function works by calculating the normal to the line, and adding that to the starting and ending point. The length of this normal is the entire `lineWidth`, meaning we are adding the `lineWidth` on both sides of the line to draw. In the image below, `n` is the normal, and since n is built such that `||n|| = lineWidth`, the total width of the line becomes double that.
This PR changes `ilxy`, which is …
> 🐛 Make lines draw at their actual line width

- .github/workflows/dotnet-publish.yml
Fixes the GitHub workflow to only publish the main library project.
We don't want to publish the example projects to GitHub.
Pass in the path to the project ([documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-pack#arguments))
N/A
Seems like explicitly controlling the packages we push isn't so bad.
N/A
N/A
> 👷‍♂️ Explicitly specify the csproj to pack for NuGet publish

- Bearded.Graphics.Examples/01.Basics/EntryPoint.cs
- Bearded.Graphics.Examples/02.IndexBuffer/EntryPoint.cs
- Bearded.Graphics.Examples/08.PostProcessing/EntryPoint.cs
- Bearded.Graphics.Examples/12.Text/EntryPoint.cs
- Bearded.Graphics.Examples/20.Mandelbrot/EntryPoint.cs
Hey, I noticed your samples didn't work. Got this error when I tried running them:
```bat
Unhandled exception. System.InvalidOperationException: Window must be initialised before running.
at Bearded.Graphics.Windowing.Window.Run() in B:\src\graphics\Bearded.Graphics\Windowing\Window.cs:line 98
at Bearded.Graphics.Examples.PostProcessing.EntryPoint.Main() in B:\src\graphics\Bearded.Graphics.Examples\08.PostProcessing\EntryPoint.cs:line 9
```
I figured out that adding a call to `GameWindow.Initialize` solves the problem.
I noticed that `GameWindow.Initialize` confusingly returns a Task, but making Main async and awaiting the task seems to freeze the window. Hence the synchronous call. I noticed you too [do this synchronously in td](https://github.com/beardgame/td/blob/722fdf5a2dea665409e8b79 …
> 🐛 Add GameWindow.Initialize call in sample projects

- Bearded.Graphics.Examples/01.Basics/EntryPoint.cs
- Bearded.Graphics.Examples/02.IndexBuffer/EntryPoint.cs
- Bearded.Graphics.Examples/03.RenderSettings/EntryPoint.cs
- Bearded.Graphics.Examples/08.PostProcessing/EntryPoint.cs
- Bearded.Graphics.Examples/12.Text/EntryPoint.cs
- Bearded.Graphics.Examples/20.Mandelbrot/EntryPoint.cs
- Bearded.Graphics/Windowing/Window.cs
This switches windowing to run on the main thread again, and GL/the actual game update loop to run on a separate thread instead.
Next to cleaning up the code a little bit more (and now no longer requiring a synchronization event or the previously added Initialize method), this is essential to make apps run on MacOS, where windowing MUST happen on the main thread.
- Removed Initialize()
- Could break some weird thread shenanigans
While I was there, I tried making the event loop more efficient by waiting for events with a timeout. empirically I don't see a difference, so I figure it's fine.
I [committed this to TD](https://github.com/beardgame/td/commit/f67c854805d22c68bc59fdde8ec49d2027ea78fa), if you'd like to test it there, but you can also check the examples (the Mandelbrot one shows …
> 🔀 Switch windowing to main thread and GL to separate one

- Bearded.Graphics/Debugging/KHRDebugExtension.cs
- Bearded.Graphics/Pipelines/Context/DebugGroup.cs
- Bearded.Graphics/Pipelines/Context/PipelineContextBuilder.cs
- Bearded.Graphics/Pipelines/Pipeline.Textures.cs
This adds (optional) [debug groups](https://www.khronos.org/opengl/wiki/Debug_Output#Scoping_messages) to our pipeline and [object labels](https://www.khronos.org/opengl/wiki/Debug_Output#Object_names) to pipeline textures and render targets.
This makes debugging in tools like RenderDoc significantly easier since it is much easier to find specific draw calls and to generally verify that intended rendering steps are happening, and in what order.
Using:
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPushDebugGroup.xhtml
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPopDebugGroup.xhtml
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glObjectLabel.xhtml
See also:
https://www.khronos.org/opengl/wiki/Debug_Output
New optional parameters are binary breaking, …
> 🏷 Add pipeline debugging

- Bearded.Graphics/Pipelines/Context/BlendMode.cs
- Bearded.Graphics/Pipelines/Context/ColorMask.cs
- Bearded.Graphics/Pipelines/Context/GLState.cs
- Bearded.Graphics/Pipelines/Context/PipelineContextBuilder.cs
- Bearded.Graphics/Pipelines/Pipeline.Extensions.cs
- Bearded.Graphics/Pipelines/Steps/WithContext.cs
This adds several small improvements to the pipeline (one commit each for easy review).
1. We now undo context changes in the opposite order in which they are applied, which means that things will work exactly as if each change was a nested WithContext call. This will also mean that we will now reset changes properly in case we make the same change twice in the same step (though I'm not sure why anyone would), instead of retaining the second to last set value. Another side effect is that the 'undo's will now be grouped in the same debug group in RenderDoc instead of in the following one, if the group debug name is set first (and hence popped last!).
2. Added color masking to pipeline context. It lets you select which of the RGBA channels you want to draw to and which not. There's another …
> 🚰 Improve Pipeline

- Bearded.Graphics/Core/RenderSettings/CompositeRenderSetting.cs
- Bearded.Graphics/Pipelines/Pipeline.Textures.cs
Passing several textures as uniforms into a render step in the pipeline is verbose. This makes that much better. It also abstracts away texture units which in most cases we don't care about having control over.
Cleaner code is nice.
Using a new CompositeRenderSetting. Pretty straight forward.
See a usage example here: https://github.com/beardgame/td/commit/c1deb05454c7bcec5aa0623a04ccc64e9fbae96b#diff-0d39857e427038652fb7d5d8f6d3da8358bc82dcc4c414e900149228ec7e6552
> 🚰 Add Pipeline.TextureUniforms

- Bearded.Graphics/Windowing/Window.cs
Makes sure all resize events happen on the UI thread. 
This is needed to not crash and burn on MacOS.
> 🪡 Ensure all resize events happen on UI thread

- .github/release.yml
- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-publish.yml
- Bearded.Graphics.Examples/01.Basics/Bearded.Graphics.Examples.01.Basics.csproj
- Bearded.Graphics.Examples/02.IndexBuffer/Bearded.Graphics.Examples.02.IndexBuffer.csproj
- Bearded.Graphics.Examples/03.RenderSettings/Bearded.Graphics.Examples.03.RenderSettings.csproj
- Bearded.Graphics.Examples/08.PostProcessing/Bearded.Graphics.Examples.08.PostProcessing.csproj
- Bearded.Graphics.Examples/12.Text/Bearded.Graphics.Examples.12.Text.csproj
- Bearded.Graphics.Examples/20.Mandelbrot/Bearded.Graphics.Examples.20.Mandelbrot.csproj
- Bearded.Graphics/Bearded.Graphics.csproj
This PR updates the .NET version to 6, since .NET 5 is no longer updated, and .NET 6 is an LTS anyway.
This PR also does some updates to the project files to ensure examples aren't packed for NuGet, and it makes the project files more consistent, including bumping the language version to 9.
Consistency is good, and the `IsPackable` property will be needed to not publish the example projects with the reusable publish workflow.
Manual editing.
.NET 5 projects will start falling back to 3.1, but 5.0 is no longer a supported version.
> 🔧 Increase .NET version to .NET 6 and clean up project files

- Bearded.Graphics.ImageSharp/Bearded.Graphics.ImageSharp.csproj
- Bearded.Graphics.SkiaSharp/Bearded.Graphics.SkiaSharp.csproj
- Bearded.Graphics.System.Drawing/Bearded.Graphics.System.Drawing.csproj
- Bearded.Graphics/Bearded.Graphics.csproj
This PR updates the OpenTK references to 4.8.
Since other Bearded libraries will continue to be up-to-date, the versions in this library also need to be updated to avoid runtime errors that are caused by the dynamic invocations of the windowing library.
I manually updated the references. I added Core and Mathematics as explicit references (which help solving ambiguous reference errors). I also removed the OpenTK dependencies from the image loading libraries, since they already get the references from the main library indirectly, and this prevents them from every going out of date.
Users will have to upgrade their own OpenTK references as well.
This was done inside the TD repository, which loads fine.
> ⬆️ Upgrade to OpenTK 4.8

- Bearded.Graphics/Windowing/Window.cs
This fixes the FPS to frame time division always being 0 when a frame rate of more than 1 is provided.
It causes infinite frame rates even when a frame rate cap is asked.
Replace the integer division by a double division.
> 🐛 Fix FPS always being unlimited

- Bearded.Graphics.Examples/01.Basics/Bearded.Graphics.Examples.01.Basics.csproj
- Bearded.Graphics.Examples/02.IndexBuffer/Bearded.Graphics.Examples.02.IndexBuffer.csproj
- Bearded.Graphics.Examples/03.RenderSettings/Bearded.Graphics.Examples.03.RenderSettings.csproj
- Bearded.Graphics.Examples/08.PostProcessing/Bearded.Graphics.Examples.08.PostProcessing.csproj
- Bearded.Graphics.Examples/12.Text/Bearded.Graphics.Examples.12.Text.csproj
- Bearded.Graphics.Examples/12.Text/UVVertexData.cs
- Bearded.Graphics.Examples/20.Mandelbrot/Bearded.Graphics.Examples.20.Mandelbrot.csproj
- Bearded.Graphics.ImageSharp/Bearded.Graphics.ImageSharp.csproj
- Bearded.Graphics.SkiaSharp/Bearded.Graphics.SkiaSharp.csproj
- Bearded.Graphics.System.Drawing/Bearded.Graphics.System.Drawing.csproj
- Bearded.Graphics/Bearded.Graphics.csproj
- Bearded.Graphics/Core/Vertices/IVertexData.cs
- Bearded.Graphics/Core/Vertices/VertexAttribute.cs
- Bearded.Graphics/Core/Vertices/VertexAttributeFormat.cs
- Bearded.Graphics/Core/Vertices/VertexAttributeTemplate.cs
- Bearded.Graphics/Core/Vertices/VertexData.cs
- Bearded.Graphics/PostProcessing/PostProcessingVertexData.cs
- Bearded.Graphics/Shapes/ColorVertexData.cs
I started with wanting to support integer vertex attributes.
Doubles looked supported but were broken because of the wrong GL method call and because of a copy-paste error.
Refamiliarising myself with the relevant GL methods, I also realised that integer normalisation works differently than I thought, and decided that it should default to not normalise anything - except Color, which is specifically intended to be normalised.
I also believed there was confusion about how byte sizes were calculated - though then realised it was working correctly after all and undid the changes, replacing the previous dictionary with a switch expression due to likely compiler optimisations.
This latter point highlights a bigger issue, which is that the vertex attribute stride is currently calculated as the …
> 🏗️ Rework vertex data

- Bearded.Graphics.ImageSharp/Bearded.Graphics.ImageSharp.csproj
- Bearded.Graphics.ImageSharp/ImageTextureData.cs
Upgrades ImageSharp to 3.1.3. This includes updating some method calls to their new signatures.
See #74 
There is a security vulnerability in ImageSharp 2 and it keeps trying to tell me everywhere 😛 
Updated the package, then resolved all build errors.
Might break compatibility with other people who use ImageSharp 2 still. TD uses 3 though.
Need to bump it somehow.
I've run a clean build of TD with this Bearded.Graphics version and it builds and runs fine. Things are drawn as expected.
> ⬆️ Upgrade to ImageSharp 3

- Bearded.Graphics/Core/BufferStream.cs
- Bearded.Graphics/Pipelines/Pipeline.Extensions.cs
- Bearded.Graphics/Pipelines/Pipeline.cs
- Bearded.Graphics/Pipelines/Steps/Composite.cs
Improves buffer and pipeline interfaces a little, primarily to use spans in some places where it makes sense.
Required for latest TD.
> Buffer improvements

- Bearded.Graphics/Bearded.Graphics.csproj
- Bearded.Graphics/Windowing/RenderDoc.Implementation.cs
- Bearded.Graphics/Windowing/RenderDoc.Load.cs
Adds API for loading RenderDoc if available, configuring basic settings, capturing frames, and automatically opening the replay ui.
I want to _always_ have access to RenderDoc when debugging TD, just in case.
Also, this way I don't have to build changes in Rider, switch to the RenderDoc UI and run from there, I can just build and run as normal, and it just works.
Using bindings generated just last week or so, here: https://github.com/EvergineTeam/RenderDoc.NET
> 📸 Add RenderDoc frame capture

- Bearded.Graphics/Pipelines/Context/BlendMode.cs
- Bearded.Graphics/Pipelines/Context/GLState.cs
What it says on the tin.
There's a lot of different blend mode combinations given the three parameters and their possible values. I want to experiment with them more freely. This allows me to do that, exposing all blend modes OpenGL supports.
Use a struct containing the actual blend more parameters instead of an enum and expose a public constructor.
Type changed from enum to struct, but maintains any reasonable-use source compatibility.
> 🛠️ Allow custom blend modes in pipeline

- .github/workflows/dotnet-build.yml
- .github/workflows/dotnet-publish.yml
This PR fixes the GitHub Actions so they actually pass.
To validate incoming PRs.
Previously the .NET version of all projects was incremented, but GH actions wasn't updated. Why the builds were green up to now is a mystery to me.
> 🐛 Fix builds by using correct .NET version
